version: '3.9'

services:

  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1F4h8k3b5t2w!
      - POSTGRES_USER=login
      - POSTGRES_DB=db
